{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "f79f2c1f-0b78-41ca-8096-956c6096f464",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting wawaw.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile wawaw.py\n",
    "import streamlit as st\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from scipy.stats import f\n",
    "from scipy.stats import t\n",
    "import math\n",
    "from scipy.stats import norm\n",
    "\n",
    "st.title(\"Kelompok 3 ChatDKT\")\n",
    "st.set_page_config(page_title=\"Aplikasi Pemilihan Uji Parametrik\", layout=\"wide\")\n",
    "\n",
    "uji = st.sidebar.radio(\"Halaman\", [\"Beranda\", \"Uji Data Kategorik\", \"Uji Data Numerik\"])\n",
    "\n",
    "if uji == \"Beranda\":\n",
    "    tab1, tab2 = st.tabs([\"Pendahuluan\",\"Credit\"])\n",
    "    with tab1:\n",
    "        st.header(\"Aplikasi Pemilihan Uji Statistika Parametrik\")\n",
    "        st.markdown(\"\"\"\n",
    "        Aplikasi ini membantu memilih dan menjalankan uji parametrik berdasarkan flowchart yang Anda miliki.\n",
    "        \n",
    "        \n",
    "        Fitur utama:\n",
    "        - Sidebar untuk navigasi.\n",
    "        - Halaman terpisah untuk setiap uji.\n",
    "        - Tabs: Penjelasan, Flowchart Uji Rumus, Contoh, Hitung Hasil.\n",
    "        - Interaktivitas: input data, pilih arah uji, lihat p-value dan nilai kritis.\n",
    "        \"\"\")\n",
    "    with tab2:\n",
    "        st.markdown(\"## 👥 Credit Pembuat Aplikasi\")\n",
    "        st.markdown(\"### Kelompok 3 — Uji Hipotesis Statistik\")\n",
    "        \n",
    "        credits = [\n",
    "            (\"Jazia Nayla Aqila\", \"14061025008\",\n",
    "             \"Pembuat Syntax Uji Rata-rata 1 Sampel (Uji Z dan Uji t)\"),\n",
    "        \n",
    "            (\"Raudhatul Azkiyah\", \"140610250019\",\n",
    "             \"Pembuat Syntax Uji Rata-rata 2 Sampel Independen – Varians Diketahui (Uji Z)\"),\n",
    "        \n",
    "            (\"Ganeza Ramadhani Wivo Putri\", \"140610250030\",\n",
    "             \"Pembuat Syntax Uji Proporsi 1 sampel dan 2 sampel\"),\n",
    "        \n",
    "            (\"Moehammad Dikta Alfikri\", \"140610250034\",\n",
    "             \"Pembuat Syntax Uji Rata-rata 2 Sampel Independen – Varians Tidak Sama (Welch t-test)\"),\n",
    "        \n",
    "            (\"Daniela Arleyne Nussy\", \"140610250046\",\n",
    "             \"Pembuat Syntax Uji Rata-rata 2 Sampel Independen – Varians Sama (Pooled t-test)\"),\n",
    "        \n",
    "            (\"Tarish Aulia Fathan\", \"140610250096\",\n",
    "             \"Pembuat Syntax Uji Rata-rata 2 Sampel Dependen (Paired t-test)\"),\n",
    "        \n",
    "            (\"Nahru Fadhilah Ramadhanu\", \"140610250116\",\n",
    "             \"Pembuat Syntax Uji Kesamaan Varians\")\n",
    "        ]\n",
    "        \n",
    "        def credit_card(name, npm, task):\n",
    "            with st.container():\n",
    "                st.subheader(f\"{name} — {npm}\")\n",
    "                st.caption(task)\n",
    "                st.divider()\n",
    "        for name, npm, task in credits:\n",
    "            credit_card(name, npm, task)\n",
    "\n",
    "\n",
    "elif uji == \"Uji Data Kategorik\":\n",
    "    tab1, tab2, tab3, tab4, tab5 = st.tabs([\"Penjelasan\",\"FlowChart Uji\",\"Rumus\",\"Contoh\",\"Hitung Hasil\"])\n",
    "    with tab1:\n",
    "        st.write(\"\"\"\n",
    "        ## Uji Proporsi 1 Sampel\n",
    "        Uji proporsi satu sampel digunakan untuk menentukan apakah proporsi populasi sama dengan nilai tertentu (p₀).\n",
    "        Data harus berupa kategori sukses/gagal.\n",
    "        Metode ini menggunakan pendekatan distribusi normal (Z) pada sampel besar.\n",
    "\n",
    "        Hipotesis umum:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: p = p_0\")\n",
    "        st.latex(r\"H_1: p \\neq p_0, p > p_0, p < p_0\")\n",
    "        st.header(\"\")\n",
    "        st.write(\"\"\"\n",
    "        ## Uji Proporsi 2 Sampel\n",
    "        Uji ini digunakan untuk membandingkan dua proporsi populasi berdasarkan\n",
    "        dua sampel independen. Statistik uji menggunakan distribusi Z.\n",
    "\n",
    "        Hipotesis umum:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: p = p_0\")\n",
    "        st.latex(r\"H_1: p_1 \\neq p_2, p_1 > p_2, p_1 < p_2\")\n",
    "    with tab2:\n",
    "        st.image(\"https://i.imgur.com/X27YksH.jpeg\", use_container_width=True)\n",
    "    with tab3:\n",
    "        st.header(\"Uji Proporsi 1 Sampel\")\n",
    "        st.subheader(\"1. Hitung Proporsi Sampel:\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{x}{n}\")\n",
    "        st.subheader(\"2. Hitung Statistik Uji Z:\")\n",
    "        st.latex(r\"Z = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0(1-p_0)}{n}}}\")\n",
    "        st.header(\"\")\n",
    "        st.header(\"Uji Proporsi 2 Sampel\")\n",
    "        st.subheader(\"1. Hitung Proporsi Sampel:\")\n",
    "        st.latex(r\"\\hat{p}_1 = \\frac{x_1}{n_1}\")\n",
    "        st.latex(r\"\\hat{p}_2 = \\frac{x_2}{n_2}\")\n",
    "        st.subheader(\"2. Hitung Proporsi Gabungan (pooled proportion):\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{x_1 + x_2}{n_1 + n_2}\")\n",
    "        st.subheader(\"2 Hitung Statistik Uji Z:\")\n",
    "        st.latex(r\"Z = \\frac{\\hat{p}_1 - \\hat{p}_2}{\\sqrt{\\hat{p}(1-\\hat{p})(\\frac{1}{n_1} + \\frac{1}{n_2})}}\")\n",
    "                  \n",
    "    with tab4:\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Proporsi 1 Sampel\n",
    "        #### Diketahui 128 dari 200 produk lolos QC. Perusahaan mengklaim proporsi sebenarnya adalah 0.70. Uji apakah berbeda dari 0.70.\n",
    "        \"\"\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{128}{200} = 0.64\")\n",
    "        st.latex(r\"Z = \\frac{0.64 - 0.70}{\\sqrt{\\frac{0.70(0.30)}{200}}} = -2.94\")\n",
    "        st.markdown(\"\"\"\n",
    "        Keputusan : \n",
    "        |Z| = 2.94 > 1.96 => Tolak H₀ -> terbukti berbeda (kedua proporsi dianggap berbeda secara signifikan pada α=0.05).\n",
    "        \"\"\")\n",
    "        st.header(\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Proporsi 2 Sampel\n",
    "        #### Metode A: 44 sukses dari 80.\\n\n",
    "        #### Metode B: 30 sukses dari 70.\n",
    "        \"\"\")\n",
    "        st.latex(r\"\\hat{p}_1 = \\frac{44}{80} = 0.55, \\quad \\hat{p}_2 = \\frac{30}{70} \\approx 0.4286\")\n",
    "        st.latex(r\"\\hat{p} = \\frac{44+30}{80+70} = \\frac{74}{150} \\approx 0.4933333333 \")\n",
    "        st.latex(r\"Z = \\frac{0.55 - 0.4286}{\\sqrt{0.4933333333(0.5066666667)(\\frac{1}{80} + \\frac{1}{70})}} = 1.4840\")\n",
    "        st.markdown(\"\"\"\n",
    "        Keputusan : \n",
    "        |Z| = 1.484 < 1.96 => Gagal Menolak H₀ -> tidak signifikan (kedua proporsi dianggap tidak berbeda secara signifikan pada α=0.05).\n",
    "        \"\"\")\n",
    "    with tab5:\n",
    "        st.subheader(\"Input Data Kategori\")\n",
    "        sukses = st.number_input(\"Jumlah kategori yang dihitung sebagai 'sukses' (X):\", min_value=0, value=0)\n",
    "        total1 = st.number_input(\"Jumlah total sampel (n1):\", min_value=1, value=1)\n",
    "        \n",
    "        alpha = st.number_input(\"Nilai alpha :\", min_value=0.001, max_value=0.5, value=0.05, step=0.01)\n",
    "        \n",
    "        st.subheader(\"Pilih Jenis Uji Proporsi\")\n",
    "        uji = st.selectbox(\"Jenis uji:\", [\"Uji Proporsi 1 Sampel\", \"Uji Proporsi 2 Sampel\"])\n",
    "        \n",
    "        if uji == \"Uji Proporsi 1 Sampel\":\n",
    "            st.write(\"### Menentukan Hipotesis\")\n",
    "            p0 = st.number_input(\"Masukkan nilai proporsi pembanding (p0) :\", min_value=0.0, max_value=1.0, value=0.5)\n",
    "        \n",
    "            bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                \"Dua Arah: H1 : p ≠ p0\",\n",
    "                \"Satu Arah: H1 : p < p0\",\n",
    "                \"Satu Arah: H1 : p > p0\"\n",
    "            ])\n",
    "        \n",
    "            if st.button(\"Hitung Uji Proporsi 1 Sampel\"):\n",
    "                p_hat = sukses / total1\n",
    "                z_stat = (p_hat - p0) / np.sqrt(p0 * (1 - p0) / total1)\n",
    "        \n",
    "                \n",
    "                if bentuk_hipotesis == \"Dua Arah: H1 : p ≠ p0\":\n",
    "                    p_value = 2 * (1 - norm.cdf(abs(z_stat)))\n",
    "                    z_crit = norm.ppf(1 - alpha / 2)\n",
    "                    keputusan_daerah = f\"|Z| > {z_crit:.3f}\"\n",
    "        \n",
    "                elif bentuk_hipotesis == \"Satu Arah: H1 : p < p0\":\n",
    "                    p_value = norm.cdf(z_stat)\n",
    "                    z_crit = norm.ppf(alpha)\n",
    "                    keputusan_daerah = f\"Z < {z_crit:.3f}\"\n",
    "        \n",
    "                else:\n",
    "                    p_value = 1 - norm.cdf(z_stat)\n",
    "                    z_crit = norm.ppf(1 - alpha)\n",
    "                    keputusan_daerah = f\"Z > {z_crit:.3f}\"\n",
    "        \n",
    "                \n",
    "                st.write(\"## Hasil Uji Proporsi 1 Sampel\")\n",
    "                st.write(f\"Proporsi sampel p̂ = {p_hat:.4f}\")\n",
    "                st.write(f\"Z hitung = {z_stat:.4f}\")\n",
    "                st.write(f\"P-value = {p_value:.4f}\")\n",
    "                st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "        \n",
    "                \n",
    "                st.write(\"### Kesimpulan:\")\n",
    "                if p_value < alpha:\n",
    "                    st.success(\"Tolak H0 → Proporsi populasi *berbeda* dari p0.\")\n",
    "                else:\n",
    "                    st.info(\"Gagal menolak H0 → Tidak ada bukti proporsi populasi berbeda dari p0.\")\n",
    "        \n",
    "        else:\n",
    "            st.subheader(\"Input Data Sampel 2\")\n",
    "            sukses2 = st.number_input(\"Jumlah kategori yang dihitung sebagai 'sukses ke-2' (x₂):\", min_value=0, value=0)\n",
    "            total2 = st.number_input(\"Jumlah total sampel 2 (n2):\", min_value=1, value=1)\n",
    "        \n",
    "            bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                \"Dua Arah: H1 : p1 ≠ p2\",\n",
    "                \"Satu Arah: H1 : p1 < p2\",\n",
    "                \"Satu Arah: H1 : p1 > p2\"\n",
    "            ], key=\"uji2\")\n",
    "        \n",
    "            if st.button(\"Hitung Uji Proporsi 2 Sampel\"):\n",
    "                p1 = sukses / total1\n",
    "                p2 = sukses2 / total2\n",
    "        \n",
    "                \n",
    "                p_pool = (sukses + sukses2) / (total1 + total2)\n",
    "                z_stat = (p1 - p2) / np.sqrt(p_pool*(1 - p_pool)*((1/total1) + (1/total2)))\n",
    "        \n",
    "                \n",
    "                if bentuk_hipotesis == \"Dua Arah: H1 : p1 ≠ p2\":\n",
    "                    p_value = 2 * (1 - norm.cdf(abs(z_stat)))\n",
    "                    z_crit = norm.ppf(1 - alpha/2)\n",
    "                    keputusan_daerah = f\"|Z| > {z_crit:.3f}\"\n",
    "        \n",
    "                elif bentuk_hipotesis == \"Satu Arah: H1 : p1 < p2\":\n",
    "                    p_value = norm.cdf(z_stat)\n",
    "                    z_crit = norm.ppf(alpha)\n",
    "                    keputusan_daerah = f\"Z < {z_crit:.3f}\"\n",
    "        \n",
    "                else:\n",
    "                    p_value = 1 - norm.cdf(z_stat)\n",
    "                    z_crit = norm.ppf(1 - alpha)\n",
    "                    keputusan_daerah = f\"Z > {z_crit:.3f}\"\n",
    "        \n",
    "                \n",
    "                st.write(\"## Hasil Uji Proporsi 2 Sampel\")\n",
    "                st.write(f\"p̂₁ = {p1:.4f}   ,   p̂₂ = {p2:.4f}\")\n",
    "                st.write(f\"Z hitung = {z_stat:.4f}\")\n",
    "                st.write(f\"P-value = {p_value:.4f}\")\n",
    "                st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "        \n",
    "                \n",
    "                st.write(\"### Kesimpulan:\")\n",
    "                if p_value < alpha:\n",
    "                    st.success(\"Tolak H0 → Proporsi kedua populasi *berbeda signifikan*.\")\n",
    "                else:\n",
    "                    st.info(\"Gagal menolak H0 → Tidak ada bukti proporsi kedua populasi berbeda.\")\n",
    "else :\n",
    "    tab1, tab2, tab3, tab4, tab5 = st.tabs([\"Penjelasan\",\"FlowChart Uji\",\"Rumus\",\"Contoh\",\"Hitung Hasil\"])\n",
    "    with tab1:\n",
    "        st.write(\"\"\"\n",
    "        ## Uji Rata-Rata 1 Sampel\n",
    "        Uji rata-rata satu sampel digunakan untuk menentukan apakah mean populasi\n",
    "        sama dengan nilai tertentu (μ₀). Jika Varians Diketahui (σ) gunakan Uji Z, Jika varians populasi tidak diketahui\n",
    "        digunakan Uji t.\n",
    "\n",
    "        Hipotesis umum:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu = \\mu_0\")\n",
    "        st.latex(r\"H_1: \\mu \\neq \\mu_0, \\mu > \\mu_0, \\mu < \\mu_0\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.write(\"\"\"\n",
    "        ## Uji Kesamaan Varians (Uji F)\n",
    "        Uji F digunakan untuk menentukan apakah dua populasi memiliki varians yang sama.\n",
    "        Uji ini sangat penting karena hasilnya menentukan jenis uji t yang digunakan\n",
    "        (poole﻿d t-test untuk varians sama, atau Welch t-test untuk varians berbeda).\n",
    "        \n",
    "        Data berasal dari dua sampel independen.\n",
    "        \n",
    "        Hipotesis umum:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\sigma_1^2 = \\sigma_2^2\")\n",
    "        st.latex(r\"H_1: \\sigma_1^2 \\neq \\sigma_2^2,\\ \\sigma_1^2 > \\sigma_2^2,\\ \\sigma_1^2 < \\sigma_2^2\")\n",
    "\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.write(\"\"\"\n",
    "        ## Uji Dua Rata-Rata Independen\n",
    "        Uji ini digunakan untuk membandingkan dua mean populasi dari\n",
    "        dua sampel independen. Metode menggunakan distribusi t dengan\n",
    "        dua pilihan: varians sama (pooled) atau varians berbeda (Welch).\n",
    "\n",
    "        Hipotesis umum:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu_1 = \\mu_2\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\neq \\mu_2, \\mu_1 > \\mu_2, \\mu_1 < \\mu_2\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.write(\"\"\"\n",
    "        ## Uji Rata-Rata Paired (Berpasangan)\n",
    "        Digunakan untuk membandingkan dua pengukuran pada subjek yang sama,\n",
    "        misalnya sebelum-sesudah. Analisis dilakukan pada selisih d = X₁ - X₂.\n",
    "\n",
    "        Hipotesis umum:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu_d = 0\")\n",
    "        st.latex(r\"H_1: \\mu_d \\neq 0, \\mu_d > 0, \\mu_d < 0\")\n",
    "\n",
    "    with tab2:\n",
    "        st.image(\"https://i.imgur.com/X27YksH.jpeg\", use_container_width=True)\n",
    "    with tab3:\n",
    "        st.header(\"Uji Rata-Rata 1 Sampel Varians (σ) diketahui\")\n",
    "        st.subheader(\"1. Statistik Uji Z:\")\n",
    "        st.latex(r\"Z_{hitung} = \\frac{\\bar{x} - \\mu_0}{\\sigma / \\sqrt{n}}\")\n",
    "            \n",
    "        st.header(\"\")\n",
    "        st.header(\"Uji Rata-Rata 1 Sampel Varians (σ) tidak diketahui\")\n",
    "        st.subheader(\"1. Statistik Uji t:\")\n",
    "        st.latex(r\"t_{hitung} = \\frac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}\")\n",
    "        st.subheader(\"2. Derajat bebas:\")\n",
    "        st.latex(r\"df = n - 1\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.header(\"Uji Kesamaan Varians (Uji F)\")\n",
    "        st.subheader(\"1. Statistik Uji F:\")\n",
    "        st.latex(r\"F_{hitung} = \\frac{s_1^2}{s_2^2}\")\n",
    "        st.write(\"Pastikan varians yang lebih besar ditempatkan sebagai pembilang agar F ≥ 1.\")\n",
    "\n",
    "        st.subheader(\"2. Derajat bebas:\")\n",
    "        st.latex(r\"v_1 = n_1 - 1\")\n",
    "        st.latex(r\"v_2 = n_2 - 1\")\n",
    "\n",
    "        st.subheader(\"3. Kriteria Uji (dua arah):\")\n",
    "        st.latex(r\"tolak H_0  -> F_{hitung} > F_{\\alpha}(v_1, v_2)\")\n",
    "\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.header(\"Uji Dua Rata-Rata Independen (Varians Sama)\")\n",
    "        st.subheader(\"1. Rata-rata Sampel:\")\n",
    "        st.latex(r\"\\bar{x}_1, \\quad \\bar{x}_2\")\n",
    "        st.subheader(\"2. Varians Gabungan:\")\n",
    "        st.latex(r\"s_p^2 = \\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}\")\n",
    "        st.subheader(\"3. Statistik Uji t:\")\n",
    "        st.latex(r\"t = \\frac{\\bar{x}_1 - \\bar{x}_2}{s_p \\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}}\")\n",
    "        st.subheader(\"4. Derajat bebas:\")\n",
    "        st.latex(r\"df = n_1 + n_2 - 2\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.header(\"Uji Dua Rata-Rata Independen (Welch, Varians Berbeda)\")\n",
    "        st.subheader(\"1. Statistik Uji t:\")\n",
    "        st.latex(r\"t = \\frac{\\bar{x}_1 - \\bar{x}_2}{\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}}\")\n",
    "        st.subheader(\"2. Derajat bebas (Welch):\")\n",
    "        st.latex(r\"\"\"\n",
    "        df = \n",
    "        \\frac{\n",
    "        \\left( \\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2} \\right)^2\n",
    "        }{\n",
    "        \\frac{(s_1^2/n_1)^2}{n_1-1} +\n",
    "        \\frac{(s_2^2/n_2)^2}{n_2-1}\n",
    "        }\n",
    "        \"\"\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.header(\"Uji Rata-Rata Paired (Berpasangan)\")\n",
    "        st.subheader(\"1. Selisih Data:\")\n",
    "        st.latex(r\"d_i = x_{1i} - x_{2i}\")\n",
    "        st.subheader(\"2. Statistik Uji t:\")\n",
    "        st.latex(r\"t = \\frac{\\bar{d}}{s_d / \\sqrt{n}}\")\n",
    "        st.subheader(\"3. Derajat bebas:\")\n",
    "        st.latex(r\"df = n - 1\")\n",
    "        st.subheader(\"4. Standar Deviasi (sD):\")\n",
    "        st.latex(r\"\"\"\n",
    "        s_D = \\sqrt{\n",
    "        \\frac{1}{df}\n",
    "        \\left(\n",
    "        \\sum_{i=1}^{n} D_i^2\n",
    "        -\n",
    "        \\frac{\\left(\\sum_{i=1}^{n} D_i\\right)^2}{n}\n",
    "        \\right)\n",
    "        }\n",
    "        \"\"\")\n",
    "\n",
    "    with tab4:\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Kesamaan Varians (Uji F)\n",
    "        #### Diketahui dua sampel:\n",
    "        #### Sampel 1: n₁ = 20, s₁² = 16\n",
    "        #### Sampel 2: n₂ = 18, s₂² = 10\n",
    "        #### Uji apakah kedua varians sama pada α = 0.05.\n",
    "        \"\"\")\n",
    "\n",
    "        st.latex(r\"F = \\frac{s_1^2}{s_2^2} = \\frac{16}{10} = 1.6\")\n",
    "        st.latex(r\"df_1 = 19, \\quad df_2 = 17\")\n",
    "\n",
    "        st.markdown(\"\"\"\n",
    "        Misalkan batas kritis F untuk α=0.05 adalah:\n",
    "        \"\"\")\n",
    "        st.latex(r\"F_{0.05}{(19, 17)} = 0.289\")  \n",
    "        st.markdown(\"\"\"\n",
    "        Keputusan:\n",
    "        \"\"\")\n",
    "        st.latex(r\"F < F_{0.05}{{19, 17}} -> Maka Gagal Tolak H0.\")\n",
    "        st.markdown(\"\"\"\n",
    "        Artinya varians kedua populasi **tidak berbeda secara signifikan**.\n",
    "        \"\"\")\n",
    "        \n",
    "        st.header(\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Rata-Rata 1 Sampel (Uji t) (σ tidak diketahui)\n",
    "        #### Diketahui waktu tidur mahasiswa statistika (dalam jam) sebagai berikut:\n",
    "        #### [7, 6, 8, 5, 6, 7, 6, 5]\n",
    "        #### Dosen ingin menguji apakah rata-rata tidur mahasiswa berbeda dari 6,5 jam.\n",
    "        #### Gunakan α = 0.05.\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu_0 = 6.5\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne 6.5\")\n",
    "        st.write(\"Uji 2 Arah\")\n",
    "        st.latex(r\"\\bar{x} = 6.25\")\n",
    "        st.latex(r\"s = 0.866\")\n",
    "        st.latex(r\"t = \\frac{6.25 - 6.5}{0.866/\\sqrt{8}} = -0.816\")\n",
    "        st.markdown(\"\"\"\n",
    "        Keputusan : \n",
    "        tcrit = 2.365 (α/2 = 0.025)\n",
    "        |-0.816| < 2.365 ⇒ Gagal Tolak H₀.\n",
    "        \"\"\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Rata-Rata 1 Sampel (Uji Z) (σ diketahui)\n",
    "        #### Sebuah perusahaan memproduksi baterai dengan rata-rata umur pakai σ = 8 jam (diketahui).\n",
    "        #### Standar perusahaan menyatakan bahwa umur pakai rata-rata baterai harus 50 jam.\n",
    "        #### Diambil sampel 36 baterai, dan diperoleh rata-rata sampel = 47,5 jam.\n",
    "        #### Dengan α = 0,05, uji apakah umur pakai baterai lebih rendah dari standar?\n",
    "        ##### H0 dan H1:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu_0 \\ge 50\")\n",
    "        st.latex(r\"H_1: \\mu_1 < 50\")\n",
    "        st.write(\"Uji 1 Arah (Kiri)\")\n",
    "        st.latex(r\"Z = \\frac{47.5 - 50}{8/\\sqrt{36}} = -1.875\")\n",
    "        st.markdown(\"\"\"\n",
    "        Keputusan : \n",
    "        Zcrit = -1.645 (α = 0.05)\n",
    "        -1.875 < -1.645 ⇒ Tolak H₀.\n",
    "        \"\"\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        ## Uji Kesamaan Ragam (Uji F)\n",
    "        #### Dua mesin produksi menghasilkan panjang barang (cm):\n",
    "        #### Mesin A: 22, 25, 20, 21, 23\n",
    "        #### Mesin B: 18, 19, 17, 20, 21\n",
    "        #### Uji apakah varians kedua mesin sama (α = 0.05).\n",
    "        ##### H0 dan H1:\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: σ₁² = σ₂²\")\n",
    "        st.latex(r\"H_1: σ₁² \\ne σ₂²\")\n",
    "        st.write(\"Uji 2 Arah\")\n",
    "        st.write(\"Varians A = 3\")\n",
    "        st.write(\"Varians B = 2.5\")\n",
    "        st.latex(r\"F = \\frac{s_1^{2}}{s_2^{2}} = \\frac{3}{2.5} = 1.2\")\n",
    "        st.markdown(\"\"\"\n",
    "        df1 = n1 - 1 = 4\n",
    "        df2 = n2 - 1 = 4\n",
    "        \"\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        Keputusan : \n",
    "        Fcrit = F 0.05 (4, 4) = 6.39\n",
    "        1.2 < 6.39 ⇒ Gagal Tolak H₀.\n",
    "        \"\"\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Dua Rata-Rata Independen (Ragam Sama)\n",
    "        #### Grup A: n₁=30, x̄₁=80, s₁=12\n",
    "        #### Grup B: n₂=28, x̄₂=75, s₂=15\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu_0 = 6.5\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne 6.5\")\n",
    "        st.write(\"Uji 2 Arah\")\n",
    "        st.write(\"A: mean = 71.7, s1 = 2.5\")\n",
    "        st.write(\"B: mean = 63.8, s1 = 2.68\")\n",
    "        st.latex(r\"s_p^2 = \\frac{(29)(12^2)+(27)(15^2)}{30+28-2} = 186.7\")\n",
    "        st.latex(r\"t = \\frac{71.7 - 63.8}{\\sqrt{\\frac{2.5^{2}}{6}+\\frac{2.68^{2}}{5}}} = 4.82\")\n",
    "        st.markdown(\"\"\"\n",
    "        df = 8 (welch)\n",
    "        Keputusan : \n",
    "        t = 1.45 < 2.00 ⇒ Gagal menolak H₀.\n",
    "        \"\"\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Dua Rata-Rata Independen (Ragam Berbeda)\n",
    "        #### Kelas A (n1 = 6): 80, 82, 85, 78, 90, 88\n",
    "        #### Kelas B (n2 = 5): 70, 65, 72, 68, 60, 66\n",
    "        #### Gunakan α = 0.05 untuk menguji apakah nilai rata-rata kedua kelas berbeda.\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu_0 = 6.5\")\n",
    "        st.latex(r\"H_1: \\mu_1 \\ne 6.5\")\n",
    "        st.write(\"Uji 2 Arah\")\n",
    "        st.write(\"Kelas A\")\n",
    "        st.latex(r\"\\bar{x}_1 = 83.834\")\n",
    "        st.latex(r\"s^{2}_1 = 21.767\")\n",
    "        st.latex(r\"\\bar{x}_2 = 66.834\")\n",
    "        st.latex(r\"s^{2}_2 = 17.767\")\n",
    "        st.latex(r\"t = \\frac{83.834 - 66.834}{\\sqrt{(\\frac{21.767}{6}+\\frac{17.767}{6})}} = 6.6228\")\n",
    "        st.latex(r\"db = \\frac{((\\frac{21.767}{6})+(\\frac{17.767}{6}))^{2}}{(\\frac{(\\frac{21.767}{6})^{2}}{n_{1}-1})+(\\frac{(\\frac{17.767}{6})^{2}}{n_{2}-1})} \\approx 9.899\")\n",
    "        st.markdown(\"\"\"\n",
    "        t kritis = t 0.025 (df = 9.899) = 2.231\n",
    "        Keputusan : \n",
    "        t = |6.6228| > 2.231 ⇒ Tolak H₀.\n",
    "        \"\"\")\n",
    "\n",
    "        st.header(\"\")\n",
    "        st.markdown(\"\"\"\n",
    "        ## Contoh Uji Paired\n",
    "        #### Peneliti ingin menguji apakah program pelatihan meningkatkan skor tes karyawan. Diukur skor sebelum dan sesudah pelatihan pada 8 peserta:\n",
    "        #### Sebelum (X₁): 85, 88, 90, 86, 87, 89, 91, 84\n",
    "        #### Sesudah (X₂): 82, 86, 88, 85, 86, 87, 90, 83\n",
    "        #### Uji pada α = 0.05 apakah rata-rata perubahan skor berbeda dari 0. (H0: μd = 0)\n",
    "        \"\"\")\n",
    "        st.latex(r\"H_0: \\mu_d = 0\")\n",
    "        st.latex(r\"H_1: \\mu_d \\ne 0\")\n",
    "        st.write(\"Uji 2 Arah\")\n",
    "        st.latex(r\"s_d = \\sqrt{\\frac{1}{df}\\left(\\sum_{i=1}^{n} D_i^2 - \\frac{(\\sum_{i=1}^n D_i)^2}{n}\\right)} \\approx 0.744\")\n",
    "        st.write(\"dˉ=1.625\")\n",
    "        st.latex(r\"t = \\frac{1.625 - 0}{0.744/\\sqrt{8}} = 6.18\")\n",
    "        st.markdown(\"\"\"\n",
    "        df = n - 1 = 7\n",
    "        Keputusan :\n",
    "        Untuk α = 0.05 dua arah dan df = 7, t crit = t 0.025 (7) = 2.365\n",
    "        karena |6.18| > 2.365 -> Tolak H0.\n",
    "        \"\"\")\n",
    "\n",
    "    with tab5:\n",
    "        pilihh = st.selectbox(\"Mau input data apa? :\", [\"Input Raw Data\",\"Input Parameter Statistik\"])\n",
    "        if pilihh == \"Input Raw Data\":\n",
    "            a = []\n",
    "            b = []\n",
    "            \n",
    "            data1 = st.text_area(\"Masukkan Data ke 1 (contoh : 1,2,3,4,5..,dst)\")\n",
    "            if data1:\n",
    "                a = [float(x) for x in data1.split(\",\")]\n",
    "                st.write(\"Jumlah data 1 (n1) :\", len(a))\n",
    "                st.write(f\"Varians data 1 (s1^2) : {np.var(a, ddof=1)}\")\n",
    "                st.write(f\"Standar Deviasi data 1 (s1) : {np.std(a, ddof=1)}\")\n",
    "            data2 = st.text_area(\"Masukkan Data ke 2 (contoh : 1,2,3,4,5..,dst) (Jika data 1 sampel tidak perlu diisi)\")\n",
    "            if data2:\n",
    "                if data2 != \"-\":\n",
    "                    b = [float(x) for x in data2.split(\",\")]\n",
    "                    st.write(\"Jumlah data 2 (n2) :\", len(b))\n",
    "                    st.write(f\"Varians data 2 (s2^2) : {np.var(b, ddof=1)}\")\n",
    "                    st.write(f\"Standar Deviasi data 2 (s2) : {np.std(b, ddof=1)}\")\n",
    "                else:\n",
    "                    st.warning(\"Data 1 Sampel\")\n",
    "            alpha = st.number_input(\"Nilai alpha :\", min_value=0.001, max_value=0.5, value=0.05, step=0.01)\n",
    "            xbar1 = np.mean(a)\n",
    "            xbar2 = np.mean(b)\n",
    "            var1 = np.var(a, ddof=1)\n",
    "            var2 = np.var(b, ddof=1)\n",
    "            s1 = np.std(a, ddof=1)\n",
    "            s2 = np.std(b, ddof=1)\n",
    "            n1 = len(a)\n",
    "            n2 = len(b)\n",
    "            \n",
    "            if len(a) == len(b):    \n",
    "                if len(a) > 0 and len(b) > 0:\n",
    "                    dframe = pd.DataFrame({\"Data 1\": a, \"Data 2\": b})\n",
    "                    st.dataframe(dframe)\n",
    "                    st.success(\"Data 2 Sampel\")\n",
    "                    uji2 = st.selectbox(\"Apakah Data 1 dan Data 2 Independent?\", [\"Ya\",\"Tidak\"])\n",
    "                    if uji2 == \"Ya\":\n",
    "                        uji3 = st.selectbox(\"Apakah Varians Diketahui?\", [\"Ya\",\"Tidak\"])\n",
    "                        if uji3 == \"Ya\":\n",
    "                            varknow1 = st.number_input(\"Masukkan Varians data 1 yang diketahui (σ1^2)\", min_value=0.0000001)\n",
    "                            varknow2 = st.number_input(\"Masukkan Varians data 2 yang diketahui (σ2^2)\", min_value=0.0000001)\n",
    "                            \n",
    "                            def hitung_statistik_z(xbar1, xbar2, var1, var2, n1, n2):\n",
    "                                a = (xbar1-xbar2)/(np.sqrt((var1/n1)+(var2/n2)))\n",
    "                                return a\n",
    "                            z_hitung = hitung_statistik_z(xbar1, xbar2, varknow1, varknow2, n1, n2)\n",
    "                            bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                                \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                                \"Satu Arah: H1 : μ < μ0\",\n",
    "                                \"Satu Arah: H1 : μ > μ0\"\n",
    "                            ])\n",
    "                        \n",
    "                            if st.button(\"Hitung Uji Hipotesis 2 Sampel Varians Diketahui (Uji Z)\"):\n",
    "                                \n",
    "                                if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                    p_value = 2 * (1 - norm.cdf(abs(z_hitung)))\n",
    "                                    z_crit = norm.ppf(1 - alpha / 2)\n",
    "                                    keputusan_daerah = f\"|Z| > {z_crit:.3f}\"\n",
    "                        \n",
    "                                elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                    p_value = norm.cdf(z_hitung)\n",
    "                                    z_crit = norm.ppf(alpha)\n",
    "                                    keputusan_daerah = f\"Z < {z_crit:.3f}\"\n",
    "                        \n",
    "                                else:\n",
    "                                    p_value = 1 - norm.cdf(z_hitung)\n",
    "                                    z_crit = norm.ppf(1 - alpha)\n",
    "                                    keputusan_daerah = f\"Z > {z_crit:.3f}\"\n",
    "                        \n",
    "                                \n",
    "                                st.write(\"## Hasil Uji Rata-rata 2 Sampel Independen – Varians Diketahui (Uji Z)\")\n",
    "                                st.write(f\"Rata-rata data 1 (xbar 1)= {xbar1:.4f}\")\n",
    "                                st.write(f\"Rata-rata data 2 (xbar 2)= {xbar2:.4f}\")\n",
    "                                st.write(f\"Z hitung = {z_hitung:.4f}\")\n",
    "                                st.write(f\"P-value = {p_value:.4f}\")\n",
    "                                st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                        \n",
    "                                \n",
    "                                st.write(\"### Kesimpulan:\")\n",
    "                                if p_value < alpha:\n",
    "                                    st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                                else:\n",
    "                                    st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "                                \n",
    "                        else:\n",
    "                            def fcrit(alpha, var1, var2, n1, n2):\n",
    "                                if var1>var2:\n",
    "                                    a = f.ppf(1-alpha, (n1-1), (n2-1))\n",
    "                                    return a\n",
    "                                else:\n",
    "                                    a = f.ppf(1-alpha, (n2-1), (n1-1))\n",
    "                                    return a\n",
    "                            def fhitung(var1, var2):\n",
    "                                if var1>var2:\n",
    "                                    a = var1/var2\n",
    "                                    return a\n",
    "                                else:\n",
    "                                    a = var2/var1\n",
    "                                    return a\n",
    "                            f_crit = fcrit(alpha, var1, var2, n1, n2)\n",
    "                            f_hitung = fhitung(var1, var2)\n",
    "                            st.write(\"## Hasil Uji Kesamaan Varians\")\n",
    "                            st.write(f\"F Hitung = {f_hitung:.4f}\")\n",
    "                            st.write(f\"F Crit = {f_crit:.4f}\")\n",
    "                            if f_hitung > f_crit:\n",
    "                                kesimpulan = \"H0 ditolak → Varians TIDAK sama (unequal variance)\"\n",
    "                                keputusan = \"Gunakan uji t dua sampel dengan varians tidak sama (Welch).\"\n",
    "                                st.success(kesimpulan)\n",
    "                                st.warning(keputusan)\n",
    "                                def t_hitung(xbar1, var1, n1, xbar2, var2, n2):\n",
    "                                    if var1>var2:\n",
    "                                        a = (xbar1-xbar2)/((((var1)/n1)+((var2)/n2))**0.5)\n",
    "                                        return a\n",
    "                                    else:\n",
    "                                        a = (xbar2-xbar1)/((((var1)/n1)+((var2)/n2))**0.5)\n",
    "                                        return a\n",
    "                                def df_(var1, n1, var2, n2):\n",
    "                                    a = ((((var1)/(n1))+((var2)/(n2)))**2)/(((((var1)/(n1))**2)/(n1-1))+((((var2)/(n2))**2)/(n2-1)))\n",
    "                                    return a\n",
    "                                df = df_(var1, n1, var2, n2)\n",
    "                                t_hitung = t_hitung(xbar1, var1, n1, xbar2, var2, n2)\n",
    "                                bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                                    \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                                    \"Satu Arah: H1 : μ < μ0\",\n",
    "                                    \"Satu Arah: H1 : μ > μ0\"\n",
    "                                ])\n",
    "                            \n",
    "                                if st.button(\"Hitung Uji Hipotesis 2 Sampel Varians Berbeda\"):\n",
    "                                    if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                        p_value = 2 * (1 - t.cdf(abs(t_hitung), df))\n",
    "                                        t_crit = t.ppf(1-alpha/2,df)\n",
    "                                        keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                            \n",
    "                                    elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                        p_value = t.cdf(t_hitung, df)\n",
    "                                        t_crit = t.ppf(alpha,df)\n",
    "                                        keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                            \n",
    "                                    else:\n",
    "                                        p_value = 1 - t.cdf(t_hitung, df)\n",
    "                                        t_crit = t.ppf(1-alpha,df)\n",
    "                                        keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                            \n",
    "                                    \n",
    "                                    st.write(\"## Hasil Uji Rata-rata 2 Sampel Independen – Varians Tidak Sama (Welch t-test)\")\n",
    "                                    st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                                    st.write(f\"t hitung = {t_hitung:.4f}\")\n",
    "                                    st.write(f\"P-value = {p_value:.4f}\")\n",
    "                                    st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                            \n",
    "                                    \n",
    "                                    st.write(\"### Kesimpulan:\")\n",
    "                                    if p_value < alpha:\n",
    "                                        st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                                    else:\n",
    "                                        st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "            \n",
    "                            else:\n",
    "                                kesimpulan = \"H0 gagal ditolak → Varians sama (equal variance)\"\n",
    "                                keputusan = \"Gunakan uji t dua sampel dengan varians sama (t-student).\"\n",
    "                                st.success(kesimpulan)\n",
    "                                st.warning(keputusan)\n",
    "                                def t_hit(xbar1, xbar2, var1, var2, n1, n2):\n",
    "                                    def sgab(var1, n1, var2, n2):\n",
    "                                        b = np.sqrt(((n1-1)*var1 + (n2-1)*var2)/(n1+n2-2))\n",
    "                                        return b\n",
    "                                    sp = sgab(var1, n1, var2, n2)\n",
    "                                    a =(xbar1-xbar2)/(sp * np.sqrt((1/n1)+(1/n2)))\n",
    "                                    return a\n",
    "                                def df_(n1, n2):\n",
    "                                    a = n1+n2-2\n",
    "                                    return a\n",
    "                                    \n",
    "                                t_hitung = t_hit(xbar1, xbar2, var1, var2, n1, n2)\n",
    "                                df = df_(n1, n2)\n",
    "                                bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                                    \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                                    \"Satu Arah: H1 : μ < μ0\",\n",
    "                                    \"Satu Arah: H1 : μ > μ0\"\n",
    "                                ])\n",
    "                            \n",
    "                                if st.button(\"Hitung Uji Hipotesis 2 Sampel Varians Sama\"):\n",
    "                                    if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                        p_value = 2 * (1 - t.cdf(abs(t_hitung), df))\n",
    "                                        t_crit = t.ppf(1-alpha/2,df)\n",
    "                                        keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                            \n",
    "                                    elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                        p_value = t.cdf(t_hitung, df)\n",
    "                                        t_crit = t.ppf(alpha,df)\n",
    "                                        keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                            \n",
    "                                    else:\n",
    "                                        p_value = 1 - t.cdf(t_hitung, df)\n",
    "                                        t_crit = t.ppf(1-alpha,df)\n",
    "                                        keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                            \n",
    "                                    \n",
    "                                    st.write(\"## Hasil Uji Rata-rata 2 Sampel Independen – Varians Sama (Pooled t-test)\")\n",
    "                                    st.write(f\"Rata-rata data (xbar1)= {xbar1:.4f}\")\n",
    "                                    st.write(f\"Rata-rata data (xbar2)= {xbar2:.4f}\")\n",
    "                                    st.write(f\"t hitung = {t_hitung:.4f}\")\n",
    "                                    st.write(f\"P-value = {p_value:.4f}\")\n",
    "                                    st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                            \n",
    "                                    \n",
    "                                    st.write(\"### Kesimpulan:\")\n",
    "                                    if p_value < alpha:\n",
    "                                        st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                                    else:\n",
    "                                        st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "                    else:\n",
    "                        def D(data1, data2):\n",
    "                            i = []\n",
    "                            for q, w in zip(data1, data2):\n",
    "                                i.append(q-w)\n",
    "                            return i\n",
    "                        def sum_D(data1, data2):\n",
    "                            i = []\n",
    "                            for q, w in zip(data1, data2):\n",
    "                                i.append(q-w)\n",
    "                            return (sum(i))**2\n",
    "                        def sum_D2(data1, data2):\n",
    "                            i = []\n",
    "                            for q, w in zip(data1, data2):\n",
    "                                i.append((q-w)**2)\n",
    "                            return(sum(i))\n",
    "                        dataD = D(a, b)\n",
    "                        xbarD = np.mean(dataD)\n",
    "                        nD = len(dataD)\n",
    "                        df = nD-1\n",
    "                        nilai_uji = st.number_input(\"Masukkan nilai uji (μ0) :\")\n",
    "                        sD = np.sqrt((1/df)*((sum_D2(a, b))-(sum_D(a, b)/nD)))\n",
    "                        t_hitungD = (xbarD-nilai_uji)/(sD/np.sqrt(nD))\n",
    "                        bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                            \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                            \"Satu Arah: H1 : μ < μ0\",\n",
    "                            \"Satu Arah: H1 : μ > μ0\"\n",
    "                        ])\n",
    "                    \n",
    "                        if st.button(\"Hitung Uji Hipotesis 1 Sampel Varians Diketahui\"):\n",
    "                            if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                p_value = 2 * (1 - t.cdf(abs(t_hitungD), df))\n",
    "                                t_crit = t.ppf(1-alpha/2,df)\n",
    "                                keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                    \n",
    "                            elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                p_value = t.cdf(t_hitungD, df)\n",
    "                                t_crit = t.ppf(alpha,df)\n",
    "                                keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                    \n",
    "                            else:\n",
    "                                p_value = 1 - t.cdf(t_hitungD, df)\n",
    "                                t_crit = t.ppf(1-alpha,df)\n",
    "                                keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"## Hasil Uji Rata-rata 1 Sampel\")\n",
    "                            st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                            st.write(f\"Simpangan Baku D (sD)= {sD:.4f}\")\n",
    "                            st.write(f\"t hitung = {t_hitungD:.4f}\")\n",
    "                            st.write(f\"P-value = {p_value:.4f}\")\n",
    "                            st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"### Kesimpulan:\")\n",
    "                            if p_value < alpha:\n",
    "                                st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "                elif len(a) > 0 and len(b) == 0:\n",
    "                    st.success(\"Data 1 Sampel\")\n",
    "                    dframe = pd.DataFrame({\"Data 1\": a})\n",
    "                    st.dataframe(dframe)\n",
    "                    uji1 = st.selectbox(\"Apakah Varians Diketahui?\", [\"Ya\",\"Tidak\"])\n",
    "                    nilai_uji = st.number_input(\"Masukkan nilai uji (μ0) :\")\n",
    "                    if uji1 == \"Ya\":\n",
    "                        sigma = st.number_input(\"Masukkan Simpangan Baku yang diketahui (σ)\")\n",
    "                        def hitung_statistik_z(mean_x, mu0, sigma, n):\n",
    "                            return (mean_x - mu0) / (sigma / (n**0.5))\n",
    "                        z_hitung = hitung_statistik_z(xbar1, nilai_uji, sigma, n1)\n",
    "                        bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                            \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                            \"Satu Arah: H1 : μ < μ0\",\n",
    "                            \"Satu Arah: H1 : μ > μ0\"\n",
    "                        ])\n",
    "                    \n",
    "                        if st.button(\"Hitung Uji Hipotesis 1 Sampel Varians Diketahui\"):\n",
    "                            \n",
    "                            if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                p_value = 2 * (1 - norm.cdf(abs(z_hitung)))\n",
    "                                z_crit = norm.ppf(1 - alpha / 2)\n",
    "                                keputusan_daerah = f\"|Z| > {z_crit:.3f}\"\n",
    "                    \n",
    "                            elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                p_value = norm.cdf(z_hitung)\n",
    "                                z_crit = norm.ppf(alpha)\n",
    "                                keputusan_daerah = f\"Z < {z_crit:.3f}\"\n",
    "                    \n",
    "                            else:\n",
    "                                p_value = 1 - norm.cdf(z_hitung)\n",
    "                                z_crit = norm.ppf(1 - alpha)\n",
    "                                keputusan_daerah = f\"Z > {z_crit:.3f}\"\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"## Hasil Uji Rata-rata 1 Sampel\")\n",
    "                            st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                            st.write(f\"Z hitung = {z_hitung:.4f}\")\n",
    "                            st.write(f\"P-value = {p_value:.4f}\")\n",
    "                            st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"### Kesimpulan:\")\n",
    "                            if p_value < alpha:\n",
    "                                st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "            \n",
    "                    else:\n",
    "                        def hitung_df(n):\n",
    "                            return n - 1\n",
    "                        def hitung_statistik_t(mean_x, mu0, s, n):\n",
    "                            a = (mean_x - mu0)/(s/(n**0.5))\n",
    "                            return a\n",
    "            \n",
    "                        df = hitung_df(n1)\n",
    "                        t_hitung = hitung_statistik_t(xbar1, nilai_uji, s1, n1)\n",
    "                        bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                            \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                            \"Satu Arah: H1 : μ < μ0\",\n",
    "                            \"Satu Arah: H1 : μ > μ0\"\n",
    "                        ])\n",
    "                    \n",
    "                        if st.button(\"Hitung Uji Hipotesis 1 Sampel Varians Diketahui\"):\n",
    "                            if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                p_value = 2 * (1 - t.cdf(abs(t_hitung), df))\n",
    "                                t_crit = t.ppf(1-alpha/2,df)\n",
    "                                keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                    \n",
    "                            elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                p_value = t.cdf(t_hitung, df)\n",
    "                                t_crit = t.ppf(alpha,df)\n",
    "                                keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                    \n",
    "                            else:\n",
    "                                p_value = 1 - t.cdf(t_hitung, df)\n",
    "                                t_crit = t.ppf(1-alpha,df)\n",
    "                                keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"## Hasil Uji Rata-rata 1 Sampel\")\n",
    "                            st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                            st.write(f\"t hitung = {t_hitung:.4f}\")\n",
    "                            st.write(f\"P-value = {p_value:.4f}\")\n",
    "                            st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"### Kesimpulan:\")\n",
    "                            if p_value < alpha:\n",
    "                                st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "                else:\n",
    "                    st.warning(\"Tolong isi datanya untuk diproses\")\n",
    "            else:\n",
    "                if len(a) > 0 and len(b) > 0:\n",
    "                    st.warning(\"Dataframe ditampilkan jika kedua data memiliki jumlah data (n) yang sama\")\n",
    "                    uji3 = st.selectbox(\"Apakah Varians Diketahui?\", [\"Ya\",\"Tidak\"])\n",
    "                    if uji3 == \"Ya\":\n",
    "                        varknow1 = st.number_input(\"Masukkan Varians data 1 yang diketahui (σ1^2)\", min_value=0.0000001)\n",
    "                        varknow2 = st.number_input(\"Masukkan Varians data 2 yang diketahui (σ2^2)\", min_value=0.0000001)\n",
    "                        \n",
    "                        def hitung_statistik_z(xbar1, xbar2, var1, var2, n1, n2):\n",
    "                            a = (xbar1-xbar2)/(np.sqrt((var1/n1)+(var2/n2)))\n",
    "                            return a\n",
    "                        z_hitung = hitung_statistik_z(xbar1, xbar2, varknow1, varknow2, n1, n2)\n",
    "                        bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                            \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                            \"Satu Arah: H1 : μ < μ0\",\n",
    "                            \"Satu Arah: H1 : μ > μ0\"\n",
    "                        ])\n",
    "                    \n",
    "                        if st.button(\"Hitung Uji Hipotesis 2 Sampel Varians Diketahui (Uji Z)\"):\n",
    "                            \n",
    "                            if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                p_value = 2 * (1 - norm.cdf(abs(z_hitung)))\n",
    "                                z_crit = norm.ppf(1 - alpha / 2)\n",
    "                                keputusan_daerah = f\"|Z| > {z_crit:.3f}\"\n",
    "                    \n",
    "                            elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                p_value = norm.cdf(z_hitung)\n",
    "                                z_crit = norm.ppf(alpha)\n",
    "                                keputusan_daerah = f\"Z < {z_crit:.3f}\"\n",
    "                    \n",
    "                            else:\n",
    "                                p_value = 1 - norm.cdf(z_hitung)\n",
    "                                z_crit = norm.ppf(1 - alpha)\n",
    "                                keputusan_daerah = f\"Z > {z_crit:.3f}\"\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"## Hasil Uji Rata-rata 2 Sampel Independen – Varians Diketahui (Uji Z)\")\n",
    "                            st.write(f\"Rata-rata data 1 (xbar 1)= {xbar1:.4f}\")\n",
    "                            st.write(f\"Rata-rata data 2 (xbar 2)= {xbar2:.4f}\")\n",
    "                            st.write(f\"Z hitung = {z_hitung:.4f}\")\n",
    "                            st.write(f\"P-value = {p_value:.4f}\")\n",
    "                            st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"### Kesimpulan:\")\n",
    "                            if p_value < alpha:\n",
    "                                st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "                            \n",
    "                    else:\n",
    "                        def fcrit(alpha, var1, var2, n1, n2):\n",
    "                            if var1>var2:\n",
    "                                a = f.ppf(1-alpha, (n1-1), (n2-1))\n",
    "                                return a\n",
    "                            else:\n",
    "                                a = f.ppf(1-alpha, (n2-1), (n1-1))\n",
    "                                return a\n",
    "                        def fhitung(var1, var2):\n",
    "                            if var1>var2:\n",
    "                                a = var1/var2\n",
    "                                return a\n",
    "                            else:\n",
    "                                a = var2/var1\n",
    "                                return a\n",
    "                        f_crit = fcrit(alpha, var1, var2, n1, n2)\n",
    "                        f_hitung = fhitung(var1, var2)\n",
    "                        st.write(\"## Hasil Uji Kesamaan Varians\")\n",
    "                        st.write(f\"F Hitung = {f_hitung:.4f}\")\n",
    "                        st.write(f\"F Crit = {f_crit:.4f}\")\n",
    "                        if f_hitung > f_crit:\n",
    "                            kesimpulan = \"H0 ditolak → Varians TIDAK sama (unequal variance)\"\n",
    "                            keputusan = \"Gunakan uji t dua sampel dengan varians tidak sama (Welch).\"\n",
    "                            st.success(kesimpulan)\n",
    "                            st.warning(keputusan)\n",
    "                            def t_hitung(xbar1, var1, n1, xbar2, var2, n2):\n",
    "                                if var1>var2:\n",
    "                                    a = (xbar1-xbar2)/((((var1)/n1)+((var2)/n2))**0.5)\n",
    "                                    return a\n",
    "                                else:\n",
    "                                    a = (xbar2-xbar1)/((((var1)/n1)+((var2)/n2))**0.5)\n",
    "                                    return a\n",
    "                            def df_(var1, n1, var2, n2):\n",
    "                                a = ((((var1)/(n1))+((var2)/(n2)))**2)/(((((var1)/(n1))**2)/(n1-1))+((((var2)/(n2))**2)/(n2-1)))\n",
    "                                return a\n",
    "                            df = df_(var1, n1, var2, n2)\n",
    "                            t_hitung = t_hitung(xbar1, var1, n1, xbar2, var2, n2)\n",
    "                            bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                                \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                                \"Satu Arah: H1 : μ < μ0\",\n",
    "                                \"Satu Arah: H1 : μ > μ0\"\n",
    "                            ])\n",
    "                        \n",
    "                            if st.button(\"Hitung Uji Hipotesis 2 Sampel Varians Berbeda\"):\n",
    "                                if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                    p_value = 2 * (1 - t.cdf(abs(t_hitung), df))\n",
    "                                    t_crit = t.ppf(1-alpha/2,df)\n",
    "                                    keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                        \n",
    "                                elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                    p_value = t.cdf(t_hitung, df)\n",
    "                                    t_crit = t.ppf(alpha,df)\n",
    "                                    keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                        \n",
    "                                else:\n",
    "                                    p_value = 1 - t.cdf(t_hitung, df)\n",
    "                                    t_crit = t.ppf(1-alpha,df)\n",
    "                                    keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                        \n",
    "                                \n",
    "                                st.write(\"## Hasil Uji Rata-rata 2 Sampel Independen – Varians Tidak Sama (Welch t-test)\")\n",
    "                                st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                                st.write(f\"t hitung = {t_hitung:.4f}\")\n",
    "                                st.write(f\"P-value = {p_value:.4f}\")\n",
    "                                st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                        \n",
    "                                \n",
    "                                st.write(\"### Kesimpulan:\")\n",
    "                                if p_value < alpha:\n",
    "                                    st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                                else:\n",
    "                                    st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "        \n",
    "                        else:\n",
    "                            kesimpulan = \"H0 gagal ditolak → Varians sama (equal variance)\"\n",
    "                            keputusan = \"Gunakan uji t dua sampel dengan varians sama (t-student).\"\n",
    "                            st.success(kesimpulan)\n",
    "                            st.warning(keputusan)\n",
    "                            def t_hit(xbar1, xbar2, var1, var2, n1, n2):\n",
    "                                def sgab(var1, n1, var2, n2):\n",
    "                                    b = np.sqrt(((n1-1)*var1 + (n2-1)*var2)/(n1+n2-2))\n",
    "                                    return b\n",
    "                                sp = sgab(var1, n1, var2, n2)\n",
    "                                a =(xbar1-xbar2)/(sp * np.sqrt((1/n1)+(1/n2)))\n",
    "                                return a\n",
    "                            def df_(n1, n2):\n",
    "                                a = n1+n2-2\n",
    "                                return a\n",
    "                                \n",
    "                            t_hitung = t_hit(xbar1, xbar2, var1, var2, n1, n2)\n",
    "                            df = df_(n1, n2)\n",
    "                            bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                                \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                                \"Satu Arah: H1 : μ < μ0\",\n",
    "                                \"Satu Arah: H1 : μ > μ0\"\n",
    "                            ])\n",
    "                        \n",
    "                            if st.button(\"Hitung Uji Hipotesis 2 Sampel Varians Sama\"):\n",
    "                                if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                    p_value = 2 * (1 - t.cdf(abs(t_hitung), df))\n",
    "                                    t_crit = t.ppf(1-alpha/2,df)\n",
    "                                    keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                        \n",
    "                                elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                    p_value = t.cdf(t_hitung, df)\n",
    "                                    t_crit = t.ppf(alpha,df)\n",
    "                                    keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                        \n",
    "                                else:\n",
    "                                    p_value = 1 - t.cdf(t_hitung, df)\n",
    "                                    t_crit = t.ppf(1-alpha,df)\n",
    "                                    keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                        \n",
    "                                \n",
    "                                st.write(\"## Hasil Uji Rata-rata 2 Sampel Independen – Varians Sama (Pooled t-test)\")\n",
    "                                st.write(f\"Rata-rata data (xbar1)= {xbar1:.4f}\")\n",
    "                                st.write(f\"Rata-rata data (xbar2)= {xbar2:.4f}\")\n",
    "                                st.write(f\"t hitung = {t_hitung:.4f}\")\n",
    "                                st.write(f\"P-value = {p_value:.4f}\")\n",
    "                                st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                        \n",
    "                                \n",
    "                                st.write(\"### Kesimpulan:\")\n",
    "                                if p_value < alpha:\n",
    "                                    st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                                else:\n",
    "                                    st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "                    \n",
    "                elif len(a) > 0 and len(b) == 0:\n",
    "                    st.success(\"Data 1 Sampel\")\n",
    "                    dframe = pd.DataFrame({\"Data 1\": a})\n",
    "                    st.dataframe(dframe)\n",
    "                    uji1 = st.selectbox(\"Apakah Varians Diketahui?\", [\"Ya\",\"Tidak\"])\n",
    "                    nilai_uji = st.number_input(\"Masukkan nilai uji (μ0) :\")\n",
    "                    if uji1 == \"Ya\":\n",
    "                        sigma = st.number_input(\"Masukkan Simpangan Baku yang diketahui (σ)\")\n",
    "                        def hitung_statistik_z(mean_x, mu0, sigma, n):\n",
    "                            return (mean_x - mu0) / (sigma / (n**0.5))\n",
    "                        z_hitung = hitung_statistik_z(xbar1, nilai_uji, sigma, n1)\n",
    "                        bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                            \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                            \"Satu Arah: H1 : μ < μ0\",\n",
    "                            \"Satu Arah: H1 : μ > μ0\"\n",
    "                        ])\n",
    "                    \n",
    "                        if st.button(\"Hitung Uji Hipotesis 1 Sampel Varians Diketahui\"):\n",
    "                            \n",
    "                            if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                p_value = 2 * (1 - norm.cdf(abs(z_hitung)))\n",
    "                                z_crit = norm.ppf(1 - alpha / 2)\n",
    "                                keputusan_daerah = f\"|Z| > {z_crit:.3f}\"\n",
    "                    \n",
    "                            elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                p_value = norm.cdf(z_hitung)\n",
    "                                z_crit = norm.ppf(alpha)\n",
    "                                keputusan_daerah = f\"Z < {z_crit:.3f}\"\n",
    "                    \n",
    "                            else:\n",
    "                                p_value = 1 - norm.cdf(z_hitung)\n",
    "                                z_crit = norm.ppf(1 - alpha)\n",
    "                                keputusan_daerah = f\"Z > {z_crit:.3f}\"\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"## Hasil Uji Rata-rata 1 Sampel\")\n",
    "                            st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                            st.write(f\"Z hitung = {z_hitung:.4f}\")\n",
    "                            st.write(f\"P-value = {p_value:.4f}\")\n",
    "                            st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"### Kesimpulan:\")\n",
    "                            if p_value < alpha:\n",
    "                                st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "            \n",
    "                    else:\n",
    "                        def hitung_df(n):\n",
    "                            return n - 1\n",
    "                        def hitung_statistik_t(mean_x, mu0, s, n):\n",
    "                            a = (mean_x - mu0)/(s/(n**0.5))\n",
    "                            return a\n",
    "            \n",
    "                        df = hitung_df(n1)\n",
    "                        t_hitung = hitung_statistik_t(xbar1, nilai_uji, s1, n1)\n",
    "                        bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                            \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                            \"Satu Arah: H1 : μ < μ0\",\n",
    "                            \"Satu Arah: H1 : μ > μ0\"\n",
    "                        ])\n",
    "                    \n",
    "                        if st.button(\"Hitung Uji Hipotesis 1 Sampel Varians Diketahui\"):\n",
    "                            if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                                p_value = 2 * (1 - t.cdf(abs(t_hitung), df))\n",
    "                                t_crit = t.ppf(1-alpha/2,df)\n",
    "                                keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                    \n",
    "                            elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                                p_value = t.cdf(t_hitung, df)\n",
    "                                t_crit = t.ppf(alpha,df)\n",
    "                                keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                    \n",
    "                            else:\n",
    "                                p_value = 1 - t.cdf(t_hitung, df)\n",
    "                                t_crit = t.ppf(1-alpha,df)\n",
    "                                keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"## Hasil Uji Rata-rata 1 Sampel\")\n",
    "                            st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                            st.write(f\"t hitung = {t_hitung:.4f}\")\n",
    "                            st.write(f\"P-value = {p_value:.4f}\")\n",
    "                            st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                    \n",
    "                            \n",
    "                            st.write(\"### Kesimpulan:\")\n",
    "                            if p_value < alpha:\n",
    "                                st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")\n",
    "                else:\n",
    "                    st.warning(\"Tolong isi datanya untuk diproses\")\n",
    "        else:\n",
    "            st.header(\"Uji Hipotesis Berbasis Parameter (Statistik Sampel)\")\n",
    "            mode = st.selectbox(\"Pilih jenis uji:\", [\n",
    "                \"1 Sampel\",\n",
    "                \"2 Sampel\"\n",
    "            ])\n",
    "            \n",
    "            alpha = st.number_input(\"Masukkan alpha:\", min_value=0.0001, max_value=0.5, value=0.05)\n",
    "            if mode == \"1 Sampel\":\n",
    "                xbar = st.number_input(\"Rata-rata sampel (x̄):\")\n",
    "                n = st.number_input(\"Ukuran sampel (n):\", min_value=1, step=1)\n",
    "                mu0 = st.number_input(\"Nilai hipotesis (μ0):\")\n",
    "                var_known = st.selectbox(\"Apakah varians diketahui?\", [\"Ya\", \"Tidak\"])\n",
    "            \n",
    "                bentuk = st.selectbox(\"Jenis uji:\", [\n",
    "                    \"Dua Arah: H1: μ ≠ μ0\",\n",
    "                    \"Satu Arah: H1: μ < μ0\",\n",
    "                    \"Satu Arah: H1: μ > μ0\"\n",
    "                ])\n",
    "            \n",
    "                if var_known == \"Ya\":\n",
    "                    sigma = st.number_input(\"Masukkan sigma (σ):\", min_value=0.0001)\n",
    "                    z_hit = (xbar - mu0) / (sigma / (n**0.5))\n",
    "            \n",
    "                    if st.button(\"Hitung Uji Z 1 Sampel\"):\n",
    "                        if bentuk.startswith(\"Dua\"):\n",
    "                            p = 2 * (1 - norm.cdf(abs(z_hit)))\n",
    "                            z_crit = norm.ppf(1 - alpha/2)\n",
    "                            rule = f\"|Z| > {z_crit:.3f}\"\n",
    "                        elif \" < \" in bentuk:\n",
    "                            p = norm.cdf(z_hit)\n",
    "                            z_crit = norm.ppf(alpha)\n",
    "                            rule = f\"Z < {z_crit:.3f}\"\n",
    "                        else:\n",
    "                            p = 1 - norm.cdf(z_hit)\n",
    "                            z_crit = norm.ppf(1 - alpha)\n",
    "                            rule = f\"Z > {z_crit:.3f}\"\n",
    "            \n",
    "                        st.write(\"### Hasil Uji Z 1 Sampel\")\n",
    "                        st.write(f\"Z hitung = {z_hit:.4f}\")\n",
    "                        st.write(f\"p-value = {p:.4f}\")\n",
    "                        st.write(f\"Keputusan: {rule}\")\n",
    "            \n",
    "                        if p < alpha:\n",
    "                            st.success(\"Tolak H0\")\n",
    "                        else:\n",
    "                            st.info(\"Gagal menolak H0\")\n",
    "            \n",
    "                else:\n",
    "                    s = st.number_input(\"Masukkan simpangan baku sampel (s):\", min_value=0.0001)\n",
    "                    t_hit = (xbar - mu0) / (s / (n**0.5))\n",
    "                    df = n - 1\n",
    "            \n",
    "                    if st.button(\"Hitung Uji t 1 Sampel\"):\n",
    "                        if bentuk.startswith(\"Dua\"):\n",
    "                            p = 2 * (1 - t.cdf(abs(t_hit), df))\n",
    "                            t_crit = t.ppf(1 - alpha/2, df)\n",
    "                            rule = f\"|t| > {t_crit:.3f}\"\n",
    "                        elif \" < \" in bentuk:\n",
    "                            p = t.cdf(t_hit, df)\n",
    "                            t_crit = t.ppf(alpha, df)\n",
    "                            rule = f\"t < {t_crit:.3f}\"\n",
    "                        else:\n",
    "                            p = 1 - t.cdf(t_hit, df)\n",
    "                            t_crit = t.ppf(1 - alpha, df)\n",
    "                            rule = f\"t > {t_crit:.3f}\"\n",
    "            \n",
    "                        st.write(\"### Hasil Uji t 1 Sampel\")\n",
    "                        st.write(f\"t hitung = {t_hit:.4f}\")\n",
    "                        st.write(f\"p-value = {p:.4f}\")\n",
    "                        st.write(f\"Keputusan: {rule}\")\n",
    "            \n",
    "                        if p < alpha:\n",
    "                            st.success(\"Tolak H0\")\n",
    "                        else:\n",
    "                            st.info(\"Gagal menolak H0\")\n",
    "            else:\n",
    "                \n",
    "                st.subheader(\"Statistik Sampel:\")\n",
    "                bentuk = st.selectbox(\"Jenis uji:\", [\n",
    "                    \"Dua Arah: μ1 ≠ μ2\",\n",
    "                    \"Satu Arah: μ1 < μ2\",\n",
    "                    \"Satu Arah: μ1 > μ2\"\n",
    "                ])\n",
    "                jiuji = st.selectbox(\"Apakah Data 1 dan Data 2 Independent?\", [\"Ya\",\"Tidak\"])\n",
    "                if jiuji == \"Ya\":\n",
    "                    xbar1 = st.number_input(\"x̄1:\")\n",
    "                    xbar2 = st.number_input(\"x̄2:\")\n",
    "                    n1 = st.number_input(\"n1:\", min_value=2, step=1)\n",
    "                    n2 = st.number_input(\"n2:\", min_value=2, step=1)\n",
    "                    var_known = st.selectbox(\"Varians diketahui?\", [\"Ya\", \"Tidak\"])\n",
    "                    if var_known == \"Ya\":\n",
    "                        var12 = st.number_input(\"Masukkan Varians data 1 (σ1^2):\", min_value=0.0001)\n",
    "                        var22 = st.number_input(\"Masukkan Varians data 2 (σ2^2):\", min_value=0.0001)\n",
    "                \n",
    "                        z_hit = (xbar1 - xbar2) / np.sqrt((var12)/n1 + (var22)/n2)\n",
    "                \n",
    "                        if st.button(\"Hitung Uji Z 2 Sampel\"):\n",
    "                            if bentuk.startswith(\"Dua\"):\n",
    "                                p = 2*(1 - norm.cdf(abs(z_hit)))\n",
    "                            elif \" < \" in bentuk:\n",
    "                                p = norm.cdf(z_hit)\n",
    "                            else:\n",
    "                                p = 1 - norm.cdf(z_hit)\n",
    "                \n",
    "                            st.write(\"### Hasil Uji Z 2 Sampel\")\n",
    "                            st.write(f\"Z hitung = {z_hit:.4f}\")\n",
    "                            st.write(f\"P-value = {p:.4f}\")\n",
    "                \n",
    "                            if p < alpha:\n",
    "                                st.success(\"Tolak H0\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0\")\n",
    "                \n",
    "                    else:\n",
    "                        s1 = st.number_input(\"Simpangan baku sampel 1 (s1):\", min_value=0.0001)\n",
    "                        s2 = st.number_input(\"Simpangan baku sampel 2 (s2):\", min_value=0.0001)\n",
    "                        if s1**2 > s2**2:\n",
    "                            F_hit = (s1**2)/(s2**2)\n",
    "                            df1, df2 = n1-1, n2-1\n",
    "                        else:\n",
    "                            F_hit = (s2**2)/(s1**2)\n",
    "                            df1, df2 = n2-1, n1-1\n",
    "                \n",
    "                        F_crit = f.ppf(1-alpha, df1, df2)\n",
    "                        st.write(f\"F hitung = {F_hit:.4f}, F kritis = {F_crit:.4f}\")\n",
    "                \n",
    "                        if F_hit > F_crit:\n",
    "                            st.warning(\"Varians tidak sama → gunakan Welch\")\n",
    "                            # Welch\n",
    "                            t_hit = (xbar1 - xbar2) / np.sqrt((s1**2)/n1 + (s2**2)/n2)\n",
    "                            df = (((s1**2)/n1 + (s2**2)/n2)**2) / (\n",
    "                                (((s1**2)/n1)**2)/(n1-1) + (((s2**2)/n2)**2)/(n2-1)\n",
    "                            )\n",
    "                        else:\n",
    "                            st.success(\"Varians sama → gunakan pooled t-test\")\n",
    "                            sp = np.sqrt(((n1-1)*s1**2 + (n2-1)*s2**2) / (n1+n2-2))\n",
    "                            t_hit = (xbar1 - xbar2) / (sp * np.sqrt(1/n1 + 1/n2))\n",
    "                            df = n1 + n2 - 2\n",
    "                \n",
    "                        if st.button(\"Hitung Uji t 2 Sampel\"):\n",
    "                            if bentuk.startswith(\"Dua\"):\n",
    "                                p = 2*(1 - t.cdf(abs(t_hit), df))\n",
    "                            elif \" < \" in bentuk:\n",
    "                                p = t.cdf(t_hit, df)\n",
    "                            else:\n",
    "                                p = 1 - t.cdf(t_hit, df)\n",
    "                \n",
    "                            st.write(\"### Hasil Uji t 2 Sampel\")\n",
    "                            st.write(f\"t hitung = {t_hit:.4f}\")\n",
    "                            st.write(f\"df = {df:.4f}\")\n",
    "                            st.write(f\"P-value = {p:.4f}\")\n",
    "                \n",
    "                            if p < alpha:\n",
    "                                st.success(\"Tolak H0\")\n",
    "                            else:\n",
    "                                st.info(\"Gagal menolak H0\")\n",
    "                else:\n",
    "                    xbarD = st.number_input(\"Rata-rata D:\")\n",
    "                    nD = st.number_input(\"Masukkan banyaknya data:\", min_value=2, step=1)\n",
    "                    sD = st.number_input(\"Simpangan baku sampel D (sD):\", min_value=0.0001)\n",
    "                    df = nD-1\n",
    "                    nilai_uji = st.number_input(\"Masukkan nilai uji (μ0) :\")\n",
    "                    t_hitungD = (xbarD-nilai_uji)/(sD/np.sqrt(nD))\n",
    "                    bentuk_hipotesis = st.selectbox(\"Jenis uji arah:\", [\n",
    "                        \"Dua Arah: H1 : μ ≠ μ0\",\n",
    "                        \"Satu Arah: H1 : μ < μ0\",\n",
    "                        \"Satu Arah: H1 : μ > μ0\"\n",
    "                    ])\n",
    "                \n",
    "                    if st.button(\"Hitung Uji Hipotesis 1 Sampel Varians Diketahui\"):\n",
    "                        if bentuk_hipotesis == \"Dua Arah: H1 : μ ≠ μ0\":\n",
    "                            p_value = 2 * (1 - t.cdf(abs(t_hitungD), df))\n",
    "                            t_crit = t.ppf(1-alpha/2,df)\n",
    "                            keputusan_daerah = f\"|thitung| > {t_crit:.3f}\"\n",
    "                \n",
    "                        elif bentuk_hipotesis == \"Satu Arah: H1 : μ < μ0\":\n",
    "                            p_value = t.cdf(t_hitungD, df)\n",
    "                            t_crit = t.ppf(alpha,df)\n",
    "                            keputusan_daerah = f\"thitung < {t_crit:.3f}\"\n",
    "                \n",
    "                        else:\n",
    "                            p_value = 1 - t.cdf(t_hitungD, df)\n",
    "                            t_crit = t.ppf(1-alpha,df)\n",
    "                            keputusan_daerah = f\"thitung > {t_crit:.3f}\"\n",
    "                \n",
    "                        \n",
    "                        st.write(\"## Hasil Uji Rata-rata 1 Sampel\")\n",
    "                        st.write(f\"Rata-rata data (xbar)= {xbar1:.4f}\")\n",
    "                        st.write(f\"Simpangan Baku D (sD)= {sD:.4f}\")\n",
    "                        st.write(f\"t hitung = {t_hitungD:.4f}\")\n",
    "                        st.write(f\"P-value = {p_value:.4f}\")\n",
    "                        st.write(f\"Daerah keputusan: {keputusan_daerah}\")\n",
    "                \n",
    "                        \n",
    "                        st.write(\"### Kesimpulan:\")\n",
    "                        if p_value < alpha:\n",
    "                            st.success(\"Tolak H0 → μ *berbeda* dari μ0.\")\n",
    "                        else:\n",
    "                            st.info(\"Gagal menolak H0 → Tidak ada bukti μ berbeda dari μ0.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "c14b6d43-20d4-4611-aefb-6d1b2b39af50",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "^C\n"
     ]
    }
   ],
   "source": [
    "!streamlit run wawaw.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "823bb8ac-52a1-4d3a-b998-66279ec8d6c0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This application is used to convert notebook files (*.ipynb)\n",
      "        to various other formats.\n",
      "\n",
      "        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.\n",
      "\n",
      "Options\n",
      "=======\n",
      "The options below are convenience aliases to configurable class-options,\n",
      "as listed in the \"Equivalent to\" description-line of the aliases.\n",
      "To see all configurable class-options for some <cmd>, use:\n",
      "    <cmd> --help-all\n",
      "\n",
      "--debug\n",
      "    set log level to logging.DEBUG (maximize logging output)\n",
      "    Equivalent to: [--Application.log_level=10]\n",
      "--show-config\n",
      "    Show the application's configuration (human-readable format)\n",
      "    Equivalent to: [--Application.show_config=True]\n",
      "--show-config-json\n",
      "    Show the application's configuration (json format)\n",
      "    Equivalent to: [--Application.show_config_json=True]\n",
      "--generate-config\n",
      "    generate default config file\n",
      "    Equivalent to: [--JupyterApp.generate_config=True]\n",
      "-y\n",
      "    Answer yes to any questions instead of prompting.\n",
      "    Equivalent to: [--JupyterApp.answer_yes=True]\n",
      "--execute\n",
      "    Execute the notebook prior to export.\n",
      "    Equivalent to: [--ExecutePreprocessor.enabled=True]\n",
      "--allow-errors\n",
      "    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.\n",
      "    Equivalent to: [--ExecutePreprocessor.allow_errors=True]\n",
      "--stdin\n",
      "    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'\n",
      "    Equivalent to: [--NbConvertApp.from_stdin=True]\n",
      "--stdout\n",
      "    Write notebook output to stdout instead of files.\n",
      "    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]\n",
      "--inplace\n",
      "    Run nbconvert in place, overwriting the existing notebook (only\n",
      "            relevant when converting to notebook format)\n",
      "    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]\n",
      "--clear-output\n",
      "    Clear output of current file and save in place,\n",
      "            overwriting the existing notebook.\n",
      "    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]\n",
      "--coalesce-streams\n",
      "    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).\n",
      "    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]\n",
      "--no-prompt\n",
      "    Exclude input and output prompts from converted document.\n",
      "    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]\n",
      "--no-input\n",
      "    Exclude input cells and output prompts from converted document.\n",
      "            This mode is ideal for generating code-free reports.\n",
      "    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]\n",
      "--allow-chromium-download\n",
      "    Whether to allow downloading chromium if no suitable version is found on the system.\n",
      "    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]\n",
      "--disable-chromium-sandbox\n",
      "    Disable chromium security sandbox when converting to PDF..\n",
      "    Equivalent to: [--WebPDFExporter.disable_sandbox=True]\n",
      "--show-input\n",
      "    Shows code input. This flag is only useful for dejavu users.\n",
      "    Equivalent to: [--TemplateExporter.exclude_input=False]\n",
      "--embed-images\n",
      "    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.\n",
      "    Equivalent to: [--HTMLExporter.embed_images=True]\n",
      "--sanitize-html\n",
      "    Whether the HTML in Markdown cells and cell outputs should be sanitized..\n",
      "    Equivalent to: [--HTMLExporter.sanitize_html=True]\n",
      "--log-level=<Enum>\n",
      "    Set the log level by value or name.\n",
      "    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']\n",
      "    Default: 30\n",
      "    Equivalent to: [--Application.log_level]\n",
      "--config=<Unicode>\n",
      "    Full path of a config file.\n",
      "    Default: ''\n",
      "    Equivalent to: [--JupyterApp.config_file]\n",
      "--to=<Unicode>\n",
      "    The export format to be used, either one of the built-in formats\n",
      "            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']\n",
      "            or a dotted object name that represents the import path for an\n",
      "            ``Exporter`` class\n",
      "    Default: ''\n",
      "    Equivalent to: [--NbConvertApp.export_format]\n",
      "--template=<Unicode>\n",
      "    Name of the template to use\n",
      "    Default: ''\n",
      "    Equivalent to: [--TemplateExporter.template_name]\n",
      "--template-file=<Unicode>\n",
      "    Name of the template file to use\n",
      "    Default: None\n",
      "    Equivalent to: [--TemplateExporter.template_file]\n",
      "--theme=<Unicode>\n",
      "    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed\n",
      "    as prebuilt extension for the lab template)\n",
      "    Default: 'light'\n",
      "    Equivalent to: [--HTMLExporter.theme]\n",
      "--sanitize_html=<Bool>\n",
      "    Whether the HTML in Markdown cells and cell outputs should be sanitized.This\n",
      "    should be set to True by nbviewer or similar tools.\n",
      "    Default: False\n",
      "    Equivalent to: [--HTMLExporter.sanitize_html]\n",
      "--writer=<DottedObjectName>\n",
      "    Writer class used to write the\n",
      "                                        results of the conversion\n",
      "    Default: 'FilesWriter'\n",
      "    Equivalent to: [--NbConvertApp.writer_class]\n",
      "--post=<DottedOrNone>\n",
      "    PostProcessor class used to write the\n",
      "                                        results of the conversion\n",
      "    Default: ''\n",
      "    Equivalent to: [--NbConvertApp.postprocessor_class]\n",
      "--output=<Unicode>\n",
      "    Overwrite base name use for output files.\n",
      "                Supports pattern replacements '{notebook_name}'.\n",
      "    Default: '{notebook_name}'\n",
      "    Equivalent to: [--NbConvertApp.output_base]\n",
      "--output-dir=<Unicode>\n",
      "    Directory to write output(s) to. Defaults\n",
      "                                  to output to the directory of each notebook. To recover\n",
      "                                  previous default behaviour (outputting to the current\n",
      "                                  working directory) use . as the flag value.\n",
      "    Default: ''\n",
      "    Equivalent to: [--FilesWriter.build_directory]\n",
      "--reveal-prefix=<Unicode>\n",
      "    The URL prefix for reveal.js (version 3.x).\n",
      "            This defaults to the reveal CDN, but can be any url pointing to a copy\n",
      "            of reveal.js.\n",
      "            For speaker notes to work, this must be a relative path to a local\n",
      "            copy of reveal.js: e.g., \"reveal.js\".\n",
      "            If a relative path is given, it must be a subdirectory of the\n",
      "            current directory (from which the server is run).\n",
      "            See the usage documentation\n",
      "            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)\n",
      "            for more details.\n",
      "    Default: ''\n",
      "    Equivalent to: [--SlidesExporter.reveal_url_prefix]\n",
      "--nbformat=<Enum>\n",
      "    The nbformat version to write.\n",
      "            Use this to downgrade notebooks.\n",
      "    Choices: any of [1, 2, 3, 4]\n",
      "    Default: 4\n",
      "    Equivalent to: [--NotebookExporter.nbformat_version]\n",
      "\n",
      "Examples\n",
      "--------\n",
      "\n",
      "    The simplest way to use nbconvert is\n",
      "\n",
      "            > jupyter nbconvert mynotebook.ipynb --to html\n",
      "\n",
      "            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].\n",
      "\n",
      "            > jupyter nbconvert --to latex mynotebook.ipynb\n",
      "\n",
      "            Both HTML and LaTeX support multiple output templates. LaTeX includes\n",
      "            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and\n",
      "            'classic'. You can specify the flavor of the format used.\n",
      "\n",
      "            > jupyter nbconvert --to html --template lab mynotebook.ipynb\n",
      "\n",
      "            You can also pipe the output to stdout, rather than a file\n",
      "\n",
      "            > jupyter nbconvert mynotebook.ipynb --stdout\n",
      "\n",
      "            PDF is generated via latex\n",
      "\n",
      "            > jupyter nbconvert mynotebook.ipynb --to pdf\n",
      "\n",
      "            You can get (and serve) a Reveal.js-powered slideshow\n",
      "\n",
      "            > jupyter nbconvert myslides.ipynb --to slides --post serve\n",
      "\n",
      "            Multiple notebooks can be given at the command line in a couple of\n",
      "            different ways:\n",
      "\n",
      "            > jupyter nbconvert notebook*.ipynb\n",
      "            > jupyter nbconvert notebook1.ipynb notebook2.ipynb\n",
      "\n",
      "            or you can specify the notebooks list in a config file, containing::\n",
      "\n",
      "                c.NbConvertApp.notebooks = [\"my_notebook.ipynb\"]\n",
      "\n",
      "            > jupyter nbconvert --config mycfg.py\n",
      "\n",
      "To see all available configurables, use `--help-all`.\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[NbConvertApp] WARNING | pattern 'Projek' matched no files\n",
      "[NbConvertApp] WARNING | pattern 'ChatDKT-Final.ipynb' matched no files\n"
     ]
    }
   ],
   "source": [
    "!jupyter nbconvert --to python Projek ChatDKT-Final.ipynb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "31a9d466-49f2-4b95-af34-9a26094bea26",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
